# Generated by Django 4.2.10 on 2025-11-21 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_instruction', models.TextField()),
                ('ai_model', models.CharField(blank=True, max_length=100, null=True)),
                ('ai_request', models.JSONField(blank=True, null=True)),
                ('ai_response', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('success', 'success'), ('partial', 'partial'), ('failed', 'failed')], default='pending', max_length=50)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AiParsedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('inserted', 'inserted'), ('failed', 'failed')], default='pending', max_length=50)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('ai_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parsed_items', to='ai.ailog')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
